### ISSUE TITLE
fails to build on Node >= 0.12.*

### ISSUE THREAD

**Issue by morriswinkler** [MadLittleMods/node-usb-detection#24]
> usb-detection@1.0.3 preinstall /Users/user/tmp/print-manager/spark-print-mgr/node_modules/usb-detection
> node-gyp rebuild

  CXX(target) Release/obj.target/detection/src/detection.o
In file included from ../src/detection.cpp:1:
../src/detection.h:15:34: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> Find(const v8::Arguments& args);
                                 ^~~~~~~~~~~~~
                                 v8::internal::Arguments
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/detection.cpp:1:
../src/detection.h:16:15: error: unknown type name 'uv_work_t'
void EIO_Find(uv_work_t* req);
              ^
../src/detection.h:17:20: error: unknown type name 'uv_work_t'
void EIO_AfterFind(uv_work_t* req);
                   ^
../src/detection.h:19:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> StartMonitoring(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/detection.cpp:1:
../src/detection.h:21:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> StopMonitoring(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/detection.cpp:1:
../src/detection.h:35:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> RegisterAdded(const v8::Arguments& args);
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/detection.cpp:1:
../src/detection.h:37:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> RegisterRemoved(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/detection.cpp:19:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
v8::Handle<v8::Value> RegisterAdded(const v8::Arguments& args)
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/detection.cpp:21:19: error: calling a protected constructor of class 'v8::HandleScope'
  v8::HandleScope scope;
                  ^
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/detection.cpp:25:11: error: member access into incomplete type 'const v8::internal::Arguments'
  if (args.Length() == 0)
          ^
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/detection.cpp:27:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::String::New("First argument must be a function"))));
           ~~~~~ ^
../src/detection.cpp:27:28: error: no member named 'ThrowException' in namespace 'v8'
    return scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::String::New("First argument must be a function"))));
                       ~~~~^
../src/detection.cpp:27:80: error: no member named 'New' in 'v8::String'
    return scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::String::New("First argument must be a function"))));
                                                                   ~~~~~~~~~~~~^
../src/detection.cpp:30:11: error: member access into incomplete type 'const v8::internal::Arguments'
  if (args.Length() == 1)
          ^
/Users/user/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/detection.cpp:33:13: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    if(!args[0]->IsFunction())
        ~~~~^~
../src/detection.cpp:35:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::String::New("First argument must be a function"))));
               ~~~~~ ^
../src/detection.cpp:35:32: error: no member named 'ThrowException' in namespace 'v8'
        return scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::String::New("First argument must be a function"))));
                           ~~~~^
../src/detection.cpp:35:84: error: no member named 'New' in 'v8::String'
        return scope.Close(v8::ThrowException(v8::Exception::TypeError(v8::String::New("First argument must be a function"))));
                                                                       ~~~~~~~~~~~~^
../src/detection.cpp:38:20: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    callback = args[0];
               ~~~~^~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/detection/src/detection.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/tmp/print-manager/spark-print-mgr/node_modules/usb-detection
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "usb-detection"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! usb-detection@1.0.3 preinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb-detection@1.0.3 preinstall script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the usb-detection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usb-detection
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/tmp/print-manager/spark-print-mgr/npm-debug.log

please see https://github.com/jiangmiao/node-curl/issues/38

**Comment by morriswinkler** [comment]
Just figured 1.3.0 builds fine, sorry for the fuzz _)
